// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Nowcast
IntegerMatrix Nowcast(DataFrame data, Date dateAnal, DateVector NCdates, int NCsize, String reference_date, String report_date, int week_start, String unit, int nsamples);
RcppExport SEXP _RDNowcast_Nowcast(SEXP dataSEXP, SEXP dateAnalSEXP, SEXP NCdatesSEXP, SEXP NCsizeSEXP, SEXP reference_dateSEXP, SEXP report_dateSEXP, SEXP week_startSEXP, SEXP unitSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Date >::type dateAnal(dateAnalSEXP);
    Rcpp::traits::input_parameter< DateVector >::type NCdates(NCdatesSEXP);
    Rcpp::traits::input_parameter< int >::type NCsize(NCsizeSEXP);
    Rcpp::traits::input_parameter< String >::type reference_date(reference_dateSEXP);
    Rcpp::traits::input_parameter< String >::type report_date(report_dateSEXP);
    Rcpp::traits::input_parameter< int >::type week_start(week_startSEXP);
    Rcpp::traits::input_parameter< String >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(Nowcast(data, dateAnal, NCdates, NCsize, reference_date, report_date, week_start, unit, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// NowcastProb
NumericMatrix NowcastProb(DataFrame data, DateVector NCdates, int NCsize, String reference_date, String report_date, int week_start, String unit, int nsamples);
RcppExport SEXP _RDNowcast_NowcastProb(SEXP dataSEXP, SEXP NCdatesSEXP, SEXP NCsizeSEXP, SEXP reference_dateSEXP, SEXP report_dateSEXP, SEXP week_startSEXP, SEXP unitSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< DateVector >::type NCdates(NCdatesSEXP);
    Rcpp::traits::input_parameter< int >::type NCsize(NCsizeSEXP);
    Rcpp::traits::input_parameter< String >::type reference_date(reference_dateSEXP);
    Rcpp::traits::input_parameter< String >::type report_date(report_dateSEXP);
    Rcpp::traits::input_parameter< int >::type week_start(week_startSEXP);
    Rcpp::traits::input_parameter< String >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(NowcastProb(data, NCdates, NCsize, reference_date, report_date, week_start, unit, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// f_N_vec
IntegerVector f_N_vec(int x, NumericVector pvec);
RcppExport SEXP _RDNowcast_f_N_vec(SEXP xSEXP, SEXP pvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pvec(pvecSEXP);
    rcpp_result_gen = Rcpp::wrap(f_N_vec(x, pvec));
    return rcpp_result_gen;
END_RCPP
}
// f_N_arr
IntegerMatrix f_N_arr(IntegerVector xvec, NumericMatrix pmat);
RcppExport SEXP _RDNowcast_f_N_arr(SEXP xvecSEXP, SEXP pmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xvec(xvecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pmat(pmatSEXP);
    rcpp_result_gen = Rcpp::wrap(f_N_arr(xvec, pmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RDNowcast_Nowcast", (DL_FUNC) &_RDNowcast_Nowcast, 9},
    {"_RDNowcast_NowcastProb", (DL_FUNC) &_RDNowcast_NowcastProb, 8},
    {"_RDNowcast_f_N_vec", (DL_FUNC) &_RDNowcast_f_N_vec, 2},
    {"_RDNowcast_f_N_arr", (DL_FUNC) &_RDNowcast_f_N_arr, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RDNowcast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
