# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generates a vector of filled-in numbers 
#' 
#' \code{f_N_vec} returns a vector of random numbers from the distribution of the total number \code{N}, given the number of successes \code{x}
#'      and a vector of success probabilities, \code{p}. 
#' 
#' @param x Observed number 
#' @param pvec Vector of probabilities (data completeness)
#' @return Vector of same length as `pvec` of draws from the distribution of full numbers given the observed number \code{x} and the probabilities in `p`. 
#' @examples /man/examples/f_N_vec.R
#' @export
#' 
f_N_vec <- function(x, pvec) {
    .Call(`_RDNowcast_f_N_vec`, x, pvec)
}

#' Generates an array of filled-in numbers 
#' 
#' @param x Vector of observed number 
#' @param pmat Array, with same number of columns as \code{x} has elements, of probabilities (data completeness)
#' @return Array of same dimensions as \code{pmat} of full numbers given the observed numbers \code{x} and the probabilities in \code{pmat}. 
#' @examples /man/examples/f_N_arr.R
#' @export
#' 
f_N_arr <- function(xvec, pmat) {
    .Call(`_RDNowcast_f_N_arr`, xvec, pmat)
}

#' Generates data for nowcasting
NULL

NowcastDataMat <- function(df, NCstart, NCsize = 10L, NCperiod = 52L, reference_date = "reference_date", report_date = "report_date", day_anal = 5L, week_start = 2L, unit = "week") {
    .Call(`_RDNowcast_NowcastDataMat`, df, NCstart, NCsize, NCperiod, reference_date, report_date, day_anal, week_start, unit)
}

pSample <- function(x, n, nsamples = 10000L) {
    .Call(`_RDNowcast_pSample`, x, n, nsamples)
}

pSampleMult <- function(NC, nsamples = 10000L) {
    .Call(`_RDNowcast_pSampleMult`, NC, nsamples)
}

